DROP TABLE IF EXISTS books;

CREATE TABLE books(
id BIGINT PRIMARY KEY,
author_id BIGINT NOT NULL,
title VARCHAR(250) NOT NULL,
price_old VARCHAR(250) DEFAULT NULL,
price VARCHAR(250) DEFAULT NULL
);

DROP TABLE IF EXISTS authors;

CREATE TABLE authors (
	id BIGINT PRIMARY KEY,
	first_name VARCHAR(50),
	last_name VARCHAR(50)
);